-- MySQL Script generated by MySQL Workbench
-- Mon Jan  6 17:37:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema staff
-- -----------------------------------------------------
-- База для  тестов по сотрудникам

-- -----------------------------------------------------
-- Schema staff
--
-- База для  тестов по сотрудникам
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `staff` DEFAULT CHARACTER SET utf8mb4 ;
USE `staff` ;

-- -----------------------------------------------------
-- Table `staff`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`positions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_position` VARCHAR(100) NULL,
  `salary_position` SMALLINT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`head_enterptises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`head_enterptises` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name_head` VARCHAR(100) NULL,
  `id_position` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `id_position_idx` (`id_position` ASC) VISIBLE,
  CONSTRAINT `id_position`
    FOREIGN KEY (`id_position`)
    REFERENCES `staff`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`directors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name_director` VARCHAR(100) NULL,
  `id_positiond` INT UNSIGNED NOT NULL,
  `id_head` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_positiond_idx` (`id_positiond` ASC) VISIBLE,
  INDEX `id_head_idx` (`id_head` ASC) VISIBLE,
  CONSTRAINT `id_positiond`
    FOREIGN KEY (`id_positiond`)
    REFERENCES `staff`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_head`
    FOREIGN KEY (`id_head`)
    REFERENCES `staff`.`head_enterptises` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`deputys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`deputys` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name_deputy` VARCHAR(100) NULL,
  `id_positionde` INT UNSIGNED NOT NULL,
  `id_director` INT UNSIGNED NOT NULL,
  INDEX `id_director_idx` (`id_director` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `id_positionde_idx` (`id_positionde` ASC) VISIBLE,
  CONSTRAINT `id_director`
    FOREIGN KEY (`id_director`)
    REFERENCES `staff`.`directors` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `id_positionde`
    FOREIGN KEY (`id_positionde`)
    REFERENCES `staff`.`positions` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`departments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `name_head_depart` VARCHAR(100) NULL,
  `id_deputys` INT UNSIGNED NOT NULL,
  `id_posit_head` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_deputys_idx` (`id_deputys` ASC) VISIBLE,
  INDEX `id_posit_head_idx` (`id_posit_head` ASC) INVISIBLE,
  CONSTRAINT `id_deputys`
    FOREIGN KEY (`id_deputys`)
    REFERENCES `staff`.`deputys` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `id_posit_head`
    FOREIGN KEY (`id_posit_head`)
    REFERENCES `staff`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`employees` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NULL,
  `employment` TIMESTAMP(6) NULL,
  `ratio` DECIMAL(3,2) NULL,
  `id_departament` INT UNSIGNED NOT NULL,
  `id_positione` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_positione_idx` (`id_positione` ASC) VISIBLE,
  INDEX `id_departament_idx` (`id_departament` ASC) VISIBLE,
  CONSTRAINT `id_positione`
    FOREIGN KEY (`id_positione`)
    REFERENCES `staff`.`positions` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `id_departament`
    FOREIGN KEY (`id_departament`)
    REFERENCES `staff`.`departments` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
